// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SmartClinic.Domain.Entities;

public partial class Doctor
{
    [Key]
    public int Id { get; set; }

    [StringLength(100)]
    public string Name { get; set; }

    public int? DepartmentId { get; set; }
    public string? ContactNumber { get; set; }

    public bool? IsAvailable { get; set; }

    public string RoomNumber { get; set; }

    public int? ConsultationTimeInMin { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? CreatedDateTime { get; set; }

    [StringLength(50)]
    public string CreatedBy { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? UpdatedDateTime { get; set; }

    [StringLength(50)]
    public string UpdatedBy { get; set; }

    public int? UserId { get; set; }

    public virtual User User { get; set; }

    [ForeignKey("DepartmentId")]
    [InverseProperty("Doctors")]
    public virtual Department Department { get; set; }

    [InverseProperty("Doctor")]
    public virtual ICollection<Token> Tokens { get; set; } = new List<Token>();
}