// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SmartClinic.Domain.Entities;

public partial class NotificationType
{
    [Key]
    public int Id { get; set; }

    [StringLength(50)]
    public string Name { get; set; }

    [StringLength(100)]
    public string MediaType { get; set; }

    [InverseProperty("Type")]
    public virtual ICollection<Notification> Notifications { get; set; } = new List<Notification>();
}