// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SmartClinic.Domain.Entities;

public partial class Notification
{
    [Key]
    public int Id { get; set; }

    public int? PatientId { get; set; }

    [StringLength(500)]
    public string Message { get; set; }

    public int? TypeId { get; set; }

    [StringLength(50)]
    public string Status { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? CreatedAt { get; set; }

    [ForeignKey("TypeId")]
    [InverseProperty("Notifications")]
    public virtual NotificationType Type { get; set; }
}