// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SmartClinic.Domain.Entities;

public partial class Patient
{
    [Key]
    public int Id { get; set; }

    [StringLength(100)]
    public string Name { get; set; }

    [Column("DOB")]
    public DateOnly? Dob { get; set; }

    public int? Age { get; set; }
    public string Symptoms { get; set; }

    public bool IsDeleted { get; set; }

    [StringLength(10)]
    public string Gender { get; set; }

    [StringLength(15)]
    public string MobileNumber { get; set; }

    public string Email { get; set; }

    [Column("UHID")]
    [StringLength(50)]
    public string Uhid { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? CreatedDateTime { get; set; }

    [StringLength(50)]
    public string CreatedBy { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? UpdatedDateTime { get; set; }

    [StringLength(50)]
    public string UpdatedBy { get; set; }

    [InverseProperty("Patient")]
    public virtual ICollection<Token> Tokens { get; set; } = new List<Token>();
}