// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SmartClinic.Domain.Entities;

[Table("PriorityConfig")]
public partial class PriorityConfig
{
    [Key]
    public int Id { get; set; }

    [StringLength(50)]
    public string Name { get; set; }

    public int? PriorityLevel { get; set; }

    public int? MinWeight { get; set; }

    public int? MaxWeight { get; set; }

    public bool? IsDeleted { get; set; }
}