// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SmartClinic.Domain.Entities;

public partial class Symptom
{
    [Key]
    public int Id { get; set; }

    [StringLength(100)]
    public string Name { get; set; }

    public int? Weight { get; set; }

    public bool? IsDeleted { get; set; }

    [InverseProperty("Symptom")]
    public virtual ICollection<TokenSymptom> TokenSymptoms { get; set; } = new List<TokenSymptom>();
}