// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SmartClinic.Domain.Entities;

public partial class TokenSymptom
{
    [Key]
    public int Id { get; set; }

    public int? TokenId { get; set; }

    public int? SymptomId { get; set; }

    [ForeignKey("SymptomId")]
    [InverseProperty("TokenSymptoms")]
    public virtual Symptom Symptom { get; set; }

    [ForeignKey("TokenId")]
    [InverseProperty("TokenSymptoms")]
    public virtual Token Token { get; set; }
}