// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SmartClinic.Domain.Entities;

public partial class TokenStatus
{
    [Key]
    public int Id { get; set; }

    [StringLength(50)]
    public string Name { get; set; }
    public bool IsDeleted { get; set; }

    [InverseProperty("Status")]
    public virtual ICollection<Token> Tokens { get; set; } = new List<Token>();
}