// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SmartClinic.Domain.Entities;

[Index("Username", Name = "UQ__Users__536C85E402BA9942", IsUnique = true)]
public partial class User
{
    [Key]
    public int Id { get; set; }

    [StringLength(100)]
    public string Name { get; set; }

    [StringLength(50)]
    public string Username { get; set; }
    public string Email { get; set; }

    [StringLength(255)]
    public string PasswordHash { get; set; }

    public int? RoleId { get; set; }

    public bool? IsDeleted { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? CreatedDateTime { get; set; }

    [StringLength(50)]
    public string CreatedBy { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? UpdatedDateTime { get; set; }

    [StringLength(50)]
    public string UpdatedBy { get; set; }

    [ForeignKey("RoleId")]
    [InverseProperty("Users")]
    public virtual Role Role { get; set; }

    public virtual ICollection<Doctor> Doctors { get; set; }
}